### ISSUE TITLE
I cannot figure out how to contact you, so I made this issue

### ISSUE THREAD

**Issue by tjdevries** [zeertzjq/nvim-paste-fix#1]
Hey @zeertzjq :)

I cannot figure out how to get ahold of you (sent an email to your git email, but not sure if it's real email or not) so I figured I'd just make an issue on a random repo of yours and see if that works.

I was wondering if you wanted to do a short, informal interview for nvim 0.7 release party where we can just chat about a few nvim things and your history and give you a thanks for all your hard work of late :)

Anyway, we can respond in here or I can give you some other ways to contact me and we can chat elsewhere

Thanks,

TJ

**Comment by zeertzjq** [comment]
I'm afraid I'm not ready for an interview. Also I finally managed to create an account on Matrix.

**Comment by tjdevries** [comment]
No worries :) Thanks for the response
